CREATE TABLE COURSE ( 
    COURSE_ID INT(5) NOT NULL UNIQUE AUTO_INCREMENT,
    DEPARTMENT VARCHAR(64) NOT NULL,
    COURSE_NAME VARCHAR(64) NOT NULL,
    COURSE_NUMBER INT(3) NOT NULL,
    SEMESTER ENUM('Fall', 'Spring', 'Summer') NOT NULL,
    COURSE_YEAR INT(4) NOT NULL,
    PRIMARY KEY (COURSE_ID)
);

INSERT INTO COURSE (DEPARTMENT,COURSE_NAME,COURSE_NUMBER,SEMESTER,COURSE_YEAR)
VALUES ('Chemistry', 'Gen Chem I', 003, 'Spring', 2023);

INSERT INTO COURSE (DEPARTMENT,COURSE_NAME,COURSE_NUMBER,SEMESTER,COURSE_YEAR)
VALUES ('Chemistry', 'Gen Chem II', 004, 'Spring', 2023);

INSERT INTO COURSE (DEPARTMENT,COURSE_NAME,COURSE_NUMBER,SEMESTER,COURSE_YEAR)
VALUES ('Chemistry', 'Analytical Chemistry', 122, 'Spring', 2023);

INSERT INTO COURSE (DEPARTMENT,COURSE_NAME,COURSE_NUMBER,SEMESTER,COURSE_YEAR)
VALUES ('Chemistry', 'Advanced Organic Chemistry', 143, 'Spring', 2023);

CREATE TABLE STUDENT ( 
    STUDENT_ID INT(8) NOT NULL UNIQUE AUTO_INCREMENT,
    FNAME VARCHAR(64) NOT NULL,
    LNAME VARCHAR(64) NOT NULL,
    PRIMARY KEY (STUDENT_ID)
);

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Julian', 'Pressman');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Eleanor', 'Simmons');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Desmond', 'Dobbs');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Diane', 'Baratt');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Derek', 'Wadlow');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Jacob', 'Verne');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Cynthia', 'Cromwell');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Melissa', 'Caulder');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Alvin', 'Hardy');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Marie', 'Lee');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Dennis', 'Simmons');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Cindy', 'Finch');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Simon', 'Quincy');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Nina', 'Naylor');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Brendan', 'Tarbuck');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Alice', 'Quill');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Stanley', 'Williamson');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Irene', 'Thackeray');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Simon', 'Doyle');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Jennifer', 'Kendrick');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Richard', 'Houston');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Jill', 'Moran');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Brian', 'Nesmith');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Jill', 'Saddlemore');

INSERT INTO STUDENT (FNAME, LNAME)
VALUES ('Janice', 'Mulgroon');


CREATE TABLE ASSIGNMENT ( 
    ASSIGNMENT_ID INT(5) NOT NULL UNIQUE AUTO_INCREMENT,
    COURSE_ID INT(5),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    CATEGORY_ID INT(5),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
    ASSIGNMENT_NAME VARCHAR(64),
    PRIMARY KEY (ASSIGNMENT_ID)
);

INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 1, 'Quiz 1');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 1, 'Quiz 2');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 1, 'Quiz 3');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 2, 'Lab');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 3, 'HW 1');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 3, 'HW 2');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 3, 'HW 3');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 3, 'HW 4');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 4, 'Exam 1');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 4, 'Exam 2');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 5, 'Midterm');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (1, 6, 'Final');

INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 7, 'Quiz 1');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 7, 'Quiz 2');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 8, 'Lab');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 9, 'HW 1');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 9, 'HW 2');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 9, 'HW 3');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 9, 'HW 4');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 9, 'HW 5');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 10, 'Exam 1');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 10, 'Exam 2');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 11, 'Midterm');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (2, 12, 'Final');


INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 13, 'Lab 1');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 13, 'Lab 2');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 14, 'HW 1');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 14, 'HW 2');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 14, 'HW 3');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 14, 'HW 4');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 15, 'Exam 1');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 15, 'Exam 2');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 15, 'Exam 3');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 15, 'Exam 4');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 16, 'Midterm');
INSERT INTO ASSIGNMENT (COURSE_ID, CATEGORY_ID, ASSIGNMENT_NAME)
VALUES (3, 17, 'Final');



CREATE TABLE CATEGORY ( 
    CATEGORY_ID INT(5) NOT NULL UNIQUE AUTO_INCREMENT,
    COURSE_ID INT(5),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    CATEGORY_WEIGHT DECIMAL(2, 2) NOT NULL,
    CATEGORY_NAME VARCHAR(64) NOT NULL,
    PRIMARY KEY (CATEGORY_ID)
);

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (1, .05, 'Quizzes');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (1, .10, 'Labs');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (1, .15, 'Homework');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (1, .20, 'Exams');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (1, .25, 'Midterm');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (1, .25, 'Final');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (2, .05, 'Quizzes');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (2, .10, 'Labs');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (2, .05, 'Homework');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (2, .30, 'Project');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (2, .25, 'Midterm');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (2, .25, 'Final');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (3, .15, 'Labs');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (3, .15, 'Homework');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (3, .20, 'Exams');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (3, .25, 'Midterm');

INSERT INTO CATEGORY (COURSE_ID, CATEGORY_WEIGHT, CATEGORY_NAME)
VALUES (3, .25, 'Final');

CREATE TABLE ASSIGNMENT_SCORE ( 
    STUDENT_ID INT(5),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    ASSIGNMENT_ID INT(5),
    FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENT(ASSIGNMENT_ID),
    SCORE INT NOT NULL,
    PRIMARY KEY (STUDENT_ID, ASSIGNMENT_ID)
);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 1, 98);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 2, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 3, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 4, 77);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 5, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 6, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 7, 65);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 8, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 9, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 10, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 11, 60);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (1, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 1, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 2, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 3, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 4, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 5, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 6, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 7, 96);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 8, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 9, 78);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 10, 80);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 11, 50);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (2, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 1, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 2, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 3, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 4, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 5, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 6, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 7, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 8, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 9, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 10, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 11, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (3, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 1, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 2, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 3, 84);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 4, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 5, 53);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 6, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 7, 56);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 8, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 9, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 10, 73);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 11, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (4, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 1, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 2, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 3, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 4, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 5, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 6, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 7, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 8, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 9, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 10, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 11, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (5, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 1, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 2, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 3, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 4, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 5, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 6, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 7, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 8, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 9, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 10, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 11, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (6, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 1, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 2, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 3, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 4, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 5, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 6, 74);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 7, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 8, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 9, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 10, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 11, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (7, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 1, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 2, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 3, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 4, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 5, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 6, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 7, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 8, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 9, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 10, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 11, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (8, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 1, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 2, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 3, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 4, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 5, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 6, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 7, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 8, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 9, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 10, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 11, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (9, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 1, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 2, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 3, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 4, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 5, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 6, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 7, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 8, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 9, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 10, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 11, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (10, 12, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 13, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 14, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 15, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 16, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 17, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 18, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 19, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 20, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 21, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 22, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 23, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (11, 24, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 13, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 14, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 15, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 16, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 17, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 18, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 19, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 20, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 21, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 22, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 23, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (12, 24, 70);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 13, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 14, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 15, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 16, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 17, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 18, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 19, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 20, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 21, 72);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 22, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 23, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (13, 24, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 13, 80);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 14, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 15, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 16, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 17, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 18, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 19, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 20, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 21, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 22, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 23, 80);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (14, 24, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 13, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 14, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 15, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 16, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 17, 53);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 18, 54);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 19, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 20, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 21, 52);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 22, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 23, 50);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (15, 24, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 13, 60);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 14, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 15, 69);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 16, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 17, 63);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 18, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 19, 69);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 20, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 21, 62);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 22, 60);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 23, 68);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (16, 24, 60);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 13, 80);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 14, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 15, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 16, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 17, 83);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 18, 84);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 19, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 20, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 21, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 22, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 23, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (17, 24, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 13, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 14, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 15, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 16, 98);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 17, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 18, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 19, 99);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 20, 65);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 21, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 22, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 23, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (18, 24, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 13, 88);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 14, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 15, 84);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 16, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 17, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 18, 44);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 19, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 20, 65);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 21, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 22, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 23, 100);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (19, 24, 90);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 13, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 14, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 15, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 16, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 17, 73);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 18, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 19, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 20, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 21, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 22, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 23, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (20, 24, 80);


INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 25, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 26, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 27, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 28, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 29, 73);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 30, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 31, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 32, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 33, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 34, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 35, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (21, 36, 80);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 25, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 26, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 27, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 28, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 29, 73);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 30, 54);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 31, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 32, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 33, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 34, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 35, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (22, 36, 80);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 25, 72);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 26, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 27, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 28, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 29, 88);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 30, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 31, 79);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 32, 75);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 33, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 34, 850);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 35, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (23, 36, 95);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 25, 70);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 26, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 27, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 28, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 29, 73);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 30, 84);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 31, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 32, 85);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 33, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 34, 80);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 35, 80);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (24, 36, 80);

INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 25, 91);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 26, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 27, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 28, 92);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 29, 93);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 30, 94);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 31, 89);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 32, 95);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 33, 82);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 34, 90);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 35, 80);
INSERT INTO ASSIGNMENT_SCORE (STUDENT_ID, ASSIGNMENT_ID, SCORE)
VALUES (25, 36, 93);


CREATE TABLE STUDENT_COURSE_GRADE ( 
    STUDENT_ID INT(5),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    COURSE_ID INT(5),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    GRADE INT DEFAULT 0,
    PRIMARY KEY (STUDENT_ID)
);

INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (1,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (2,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (3,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (4,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (5,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (6,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (7,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (8,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (9,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (10,1);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (11,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (12,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (13,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (14,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (15,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (16,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (17,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (18,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (19,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (20,2);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (21,3);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (22,3);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (23,3);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (24,3);
INSERT INTO STUDENT_COURSE_GRADE (STUDENT_ID, COURSE_ID)
VALUES (25,3);
